// interior-place-hall.ts — interior-1 fail-closed hall re-place + warm room light.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";
const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-town-hall",LID="nx-town-hall-l",OLD="store/d9251dd0857e451f.glb",SHA="44fec27226f02b74746cac2d3d6d1a83520d927dac5c02a5486d6dcbb5271af9",LIB=`store/${SHA.slice(0,16)}.glb`,POS=[9,0,-26],YAW=-0.31322457341772525,LIGHT={id:LID,pos:[9,2.5,-26],color:0xffb066,intensity:1.7,range:6.5};
const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_hall3.glb`));const die=(s:string):never=>{throw Error(s)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6,vec=(a:any,b:number[])=>Array.isArray(a)&&a.length===b.length&&a.every((n:number,i:number)=>near(n,b[i])),bbox=(a:any,b:number[])=>Array.isArray(a)&&a.length===b.length&&a.every((n:number,i:number)=>Math.abs(n-b[i])<1e-3),eq=(a:any,b:any)=>JSON.stringify(a)===JSON.stringify(b);
if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("hall reviewed bytes drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`,{signal:AbortSignal.timeout(20_000)});if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e])) as Record<string,any>}
async function lightFold(){return await new Promise<any>((resolve,reject)=>{const ws=new WebSocket(cfg.url),out:any={},t=setTimeout(()=>reject(Error("light history timeout")),30_000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-interior-1-lightread",avatar:cfg.avatar,token:cfg.joinToken,spectate:true}));ws.onerror=()=>reject(Error("history ws"));ws.onmessage=(ev:any)=>{const m=JSON.parse(ev.data);if(m.type==="snapshot")ws.send(JSON.stringify({type:"history",verbs:["light"],limit:300}));else if(m.type==="history"){for(const z of m.entries??[]){const x=z.args??z;if(x.id!==LID)continue;for(const k of ["pos","color","intensity","range"])if(x[k]!==undefined)out[k]=x[k]}clearTimeout(t);ws.close();resolve(out)}}})}
const before=await geom(),auth=await lightFold(),e0=before[ID],l0=before[LID];if(!e0||!vec(e0.pos,POS)||!near(e0.yaw,YAW)||(e0.scale??1)!==1||![OLD,LIB].includes(e0.lib))die("hall tuple/lib drift");if(!bbox(e0.bbox?.min,[-5,-.2,-4.5])||!bbox(e0.bbox?.max,[5,6.168531894683838,4.853924751281738]))die("hall footprint/bounds drift");const bag=structuredClone(e0.comp??{});if(l0&&!(l0.kind==="light"&&vec(l0.pos,LIGHT.pos)&&auth.color===LIGHT.color&&near(auth.intensity,LIGHT.intensity)&&near(auth.range,LIGHT.range)))die("hall light drift");
const verbs:Array<[string,any]>=[];if(e0.lib!==LIB){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","commons-next hall interior-1");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await Bun.sleep(25_000);continue}die(`upload ${r.status}`)}if(lib!==LIB)die(`upload path ${lib}`);verbs.push(["spawn",{id:ID,lib:LIB,pos:POS,yaw:YAW,scale:1}]);for(const[type,data]of Object.entries(bag))verbs.push(["comp",{id:ID,type,data}])}if(!l0)verbs.push(["light",LIGHT]);
if(verbs.length)await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let joined=false,i=0;const t=setTimeout(()=>reject(Error("verb timeout")),90_000),paced=setInterval(()=>{if(!joined||i>=verbs.length)return;const[verb,args]=verbs[i++];ws.send(JSON.stringify({type:"verb",verb,args}));if(i===verbs.length)setTimeout(()=>{clearInterval(paced);clearTimeout(t);ws.close();resolve()},1800)},650);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-interior-1-place",avatar:cfg.avatar,token:cfg.joinToken}));ws.onerror=()=>reject(Error("websocket"));ws.onmessage=(ev:any)=>{const m=JSON.parse(ev.data);if(m.type==="error")reject(Error(`server ${m.error}`));else if(m.type==="snapshot")joined=true}});
const after=await geom(),afterAuth=await lightFold(),e=after[ID],l=after[LID];if(!(e?.lib===LIB&&vec(e.pos,POS)&&near(e.yaw,YAW)&&e.scale===1&&eq(e.comp??{},bag)))die("post hall tuple/comp");if(!(l?.kind==="light"&&vec(l.pos,LIGHT.pos)&&afterAuth.color===LIGHT.color&&near(afterAuth.intensity,LIGHT.intensity)&&near(afterAuth.range,LIGHT.range)))die("post hall light");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,compKeys:Object.keys(e.comp??{}).sort(),light:{id:LID,...afterAuth},verbs:verbs.length}));
