// next-place-artwalk-h7.ts — artwalk-8 Night Table observatory rollout.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-artwalk-h7",LIGHT_ID=`${ID}-l`,SHA="7baac8fd9b45bc923faaae427abec3bc41fd0c7a9fccba381fdff7d405835ca0",PX=31.819805153394636,PY=-0.037292896876929355,PZ=-43.13351365237939,YAW=-0.7853981633974483;
const MINX=-2.200000047683716,MAXX=2.200000047683716,MINZ=-2.200000047683716,MAXZ=5.100000002980233,BW=MAXX-MINX,BD=MAXZ-MINZ,CX=0,CZ=(MINZ+MAXZ)/2,LIGHT_POS=[30.476302269140195,2.2827071031230703,-41.79001076812495]as const,MOTION={type:"spin",axis:"y",degPerSec:-0.8};
const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_artwalk_h7.glb`));const die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("reviewed GLB hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e]))as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const cc=Math.cos(YAW),ss=Math.sin(YAW),target=O(PX+CX*cc+CZ*ss,PZ-CX*ss+CZ*cc,YAW,BW,BD),want={lib:`store/${SHA.slice(0,16)}.glb`,pos:[PX,PY,PZ],yaw:YAW,scale:1};const motionOK=(e:any)=>JSON.stringify(e?.comp?.["motion:scope"])===JSON.stringify(MOTION),tupleOK=(e:any)=>!!e&&e.lib===want.lib&&e.pos.every((n:number,i:number)=>near(n,want.pos[i]))&&near(e.yaw??0,YAW)&&e.scale===1&&motionOK(e)&&Object.keys(e.comp??{}).length===1,lightOK=(e:any)=>!!e&&e.kind==="light"&&e.pos.every((n:number,i:number)=>near(n,LIGHT_POS[i]));
const before=await geom(),existing=before[ID],existingLight=before[LIGHT_ID];if(existing&&!tupleOK(existing))die(`${ID} id collision/drift`);if(existingLight&&!lightOK(existingLight))die(`${LIGHT_ID} collision/drift`);if(!!existing!==!!existingLight)die("partial prior rollout");let inner=Infinity,outer=0;for(const[lx,lz]of[[MINX,MINZ],[MAXX,MINZ],[MAXX,MAXZ],[MINX,MAXZ]]){const wx=PX+lx*cc+lz*ss,wz=PZ-lx*ss+lz*cc,r=Math.hypot(wx,wz);inner=Math.min(inner,r);outer=Math.max(outer,r)}if(inner<30||outer>65)die(`art corridor violated ${inner}..${outer}`);
const groundIds=new Set(["nx-core-paths","nx-town-roads"]);let minGap=Infinity,minAgainst="";for(const e of Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID)){const h=e.bbox.max[1]-e.bbox.min[1];if(groundIds.has(e.id)||h<=0.5)continue;const g=gap(target,EO(e));if(g<minGap){minGap=g;minAgainst=e.id}if(g<-.001)die(`footprint overlaps ${e.id}: ${g}`)}if(minGap<1.4)die(`walkable lane pinch ${minGap} against ${minAgainst}`);console.log(JSON.stringify({stage:"preflight",centerRadius:+Math.hypot(PX,PZ).toFixed(6),corridor:{inner:+inner.toFixed(6),outer:+outer.toFixed(6)},minGap:+minGap.toFixed(6),minAgainst,nativeVisual:"waived-by-Bill"}));
if(!existing){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","the night table — artwalk H-6b");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==want.lib)die(`upload path ${lib}`);const verbs:[string,any][]=[["spawn",{id:ID,lib,pos:[PX,PY,PZ],yaw:YAW,scale:1}],["comp",{id:ID,type:"motion:scope",data:MOTION}],["light",{id:LIGHT_ID,pos:LIGHT_POS,color:0xffc98a,intensity:1.45,range:5.4}]];await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let joined=false,i=0;const timer=setTimeout(()=>reject(Error("verb timeout")),45_000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-artwalk-h7-builder",avatar:cfg.avatar,token:cfg.joinToken}));ws.onerror=()=>reject(Error("websocket error"));ws.onmessage=(ev:any)=>{const x=JSON.parse(ev.data);if(x.type==="error")reject(Error(`server ${x.error}`));else if(x.type==="snapshot"&&!joined){joined=true;const paced=setInterval(()=>{if(i>=verbs.length){clearInterval(paced);setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1800);return}const[verb,args]=verbs[i++];ws.send(JSON.stringify({type:"verb",verb,args}))},700)}}})}else console.log("H-7 already live — zero verbs");
const after=await geom(),e=after[ID],l=after[LIGHT_ID];if(!tupleOK(e))die("post-place model/comp tuple failed");if(!lightOK(l))die("post-place light tuple failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,scale:e.scale,bboxSize:e.bbox.size,comp:e.comp,light:{id:LIGHT_ID,pos:l.pos},verbs:existing?0:3}));
