// next-place-artwalk-b12.ts — host-rider placement for Kiln Heat Contours.
// Owns nx-artwalk-* only; nx-town-kiln remains read-only host truth.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-artwalk-b12-kiln-heat-contours",HOST="nx-town-kiln",HOST_LIB="store/4d8ef8fc0b0955de.glb",SHA="1ad2a6139373b973057e0cb0b2c26c9e4b24b7ee83d79ab8f15bfe27bc1e19a0";
const LOCAL:[number,number,number]=[0,0,1.15],cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws",""),bytes=readFileSync(`${ROOT}/agents/arthur/assets/village_artwalk_b12.glb`),near=(a:number,b:number)=>Math.abs(a-b)<1e-6,die=(m:string):never=>{throw Error(m)};
if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("local build hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`,{signal:AbortSignal.timeout(20_000)});if(!r.ok)die(`geom HTTP ${r.status}`);const d:any=await r.json();return Object.fromEntries(d.entities.map((e:any)=>[e.id,e]))as Record<string,any>}
type O={cx:number;cz:number;ux:[number,number];uz:[number,number];hx:number;hz:number};const O=(cx:number,cz:number,y:number,sx:number,sz:number):O=>({cx,cz,ux:[Math.cos(y),-Math.sin(y)],uz:[Math.sin(y),Math.cos(y)],hx:sx/2,hz:sz/2});
const gap=(a:O,b:O)=>{let best=-Infinity;for(const q of[a.ux,a.uz,b.ux,b.uz]as const){const d=Math.abs((b.cx-a.cx)*q[0]+(b.cz-a.cz)*q[1]),ra=a.hx*Math.abs(a.ux[0]*q[0]+a.ux[1]*q[1])+a.hz*Math.abs(a.uz[0]*q[0]+a.uz[1]*q[1]),rb=b.hx*Math.abs(b.ux[0]*q[0]+b.ux[1]*q[1])+b.hz*Math.abs(b.uz[0]*q[0]+b.uz[1]*q[1]);best=Math.max(best,d-ra-rb)}return best};
const u=O(0,0,0,2,2);if(!near(gap(u,O(4,0,0,2,2)),2)||!near(gap(u,O(2,0,0,2,2)),0)||gap(u,O(1,0,0,2,2))>=0)die("SAT self-test");
const before=await geom(),host=before[HOST];if(!host||host.lib!==HOST_LIB||host.scale!==1)die("kiln host drift");const yaw=host.yaw??0,c=Math.cos(yaw),s=Math.sin(yaw),pos:[number,number,number]=[host.pos[0]+LOCAL[0]*c+LOCAL[2]*s,host.pos[1]+LOCAL[1],host.pos[2]-LOCAL[0]*s+LOCAL[2]*c],want={lib:`store/${SHA.slice(0,16)}.glb`,pos,yaw,scale:1};
const ok=(e:any)=>!!e&&e.lib===want.lib&&e.pos.every((n:number,i:number)=>near(n,pos[i]))&&near(e.yaw??0,yaw)&&e.scale===1&&Object.keys(e.comp??{}).length===0;if(before[ID]&&!ok(before[ID]))die("existing B-12 entity drift");
// Idempotent path before SAT (struct-36 class) — see b11 note.
if(before[ID]&&ok(before[ID])){console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,...want,emittedVerbs:0,idempotentShortCircuit:true}));process.exit(0);}
const EO=(e:any)=>{const y=e.yaw??0,co=Math.cos(y),si=Math.sin(y),lx=(e.bbox.min[0]+e.bbox.max[0])/2,lz=(e.bbox.min[2]+e.bbox.max[2])/2;return O(e.pos[0]+lx*co+lz*si,e.pos[2]-lx*si+lz*co,y,e.bbox.size[0],e.bbox.size[2])};const cz=(-.004999999422580004+.11999999731779099)/2,target=O(pos[0]+cz*s,pos[2]+cz*c,yaw,1.5499999523162842,.12499999674037099);let nearest={id:"",gap:Infinity};for(const e of Object.values(before)as any[]){if(!e.bbox||e.id===HOST||e.id===ID||e.id==="nx-town-roads"||e.id==="nx-core-paths"||e.bbox.size[1]<=.5)continue;/* artwalk-49: approach-lane compounds exempted, lamps 15m+ away */if(e.lib&&(e.lib.startsWith("store/a27bc9a252272b12")||e.lib.startsWith("store/56b35877ecda923d")))continue;const g=gap(target,EO(e));if(g<nearest.gap)nearest={id:e.id,gap:g};if(g<-.001)die(`contours overlap non-host ${e.id}: ${g}`)}console.log(JSON.stringify({stage:"preflight",host:HOST,hostLib:HOST_LIB,local:LOCAL,pos,nearest}));
if(!before[ID]){const upload=new URL(`${base}/upload`);upload.searchParams.set("token",cfg.agentToken);upload.searchParams.set("name","Kiln Heat Contours");upload.searchParams.set("by",cfg.id);const r=await fetch(upload,{method:"POST",body:bytes,signal:AbortSignal.timeout(30_000)});if(!r.ok)die(`upload HTTP ${r.status}`);const result:any=await r.json();if(result.path!==want.lib)die(`upload path mismatch ${result.path}`);await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let sent=false;const timer=setTimeout(()=>reject(Error("spawn timeout")),20_000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-artwalk-b12-builder",avatar:cfg.avatar,token:cfg.joinToken,agentToken:cfg.agentToken}));ws.onmessage=(event:MessageEvent)=>{const m=JSON.parse(String(event.data));if(m.type==="error"){clearTimeout(timer);ws.close();reject(Error(m.error))}if(m.type==="snapshot"&&!sent){sent=true;ws.send(JSON.stringify({type:"verb",verb:"spawn",args:{id:ID,...want}}));setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1500)}}})}
const after=await geom();if(!ok(after[ID]))die("post-place tuple verification failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,...want,emittedVerbs:before[ID]?0:1}));
