// next-audit-core.ts — nvp-22 read-only full commons-next core audit.
// Exact live census, component/light contracts, model SAT, paver micro-SAT.
import{readFileSync}from"node:fs";const ROOT="/Users/t3rpz/projects/eidoverse-worlds",cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const die=(m:string):never=>{throw Error(m)},canon=(v:any):any=>Array.isArray(v)?v.map(canon):v&&typeof v==="object"?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v,eq=(a:any,b:any)=>JSON.stringify(canon(a))===JSON.stringify(canon(b));
async function census(){const r=await fetch(`${base}/geom?world=commons-next`);if(!r.ok)die(`geom ${r.status}`);const raw:any=await r.json(),entities=(raw.entities??[]).map((e:any)=>({...e,comp:e.comp??{},compKeys:Object.keys(e.comp??{}).sort()}));return{count:entities.length,entities}}
const expected:Record<string,{lib?:string,pos:number[],yaw:number,keys:string[]}>= {
 "nx-hearth":{lib:"43fcaf1442f5d6b8",pos:[0,0,0],yaw:0,keys:["motion:pz_kettle","motion:well_","particles","sockets"]},"nx-welcome":{lib:"4b94d42b9ef89826",pos:[-3,0,-4.3],yaw:.6092,keys:[]},"nx-carousel":{lib:"d41a898f3054874b",pos:[-18,.00014950061063032772,18],yaw:2.35619,keys:["motion:carousel","motion:horse_0","motion:horse_2","motion:horse_4","motion:horse_6","particles:smoke","sockets"]},
 "nx-approach-lamp-e":{lib:"409084706b801f8d",pos:[10,0,0],yaw:-Math.PI/2,keys:[]},"nx-approach-lamp-n":{lib:"409084706b801f8d",pos:[0,0,10],yaw:Math.PI,keys:[]},"nx-approach-lamp-w":{lib:"409084706b801f8d",pos:[-10,0,0],yaw:Math.PI/2,keys:[]},"nx-approach-lamp-s":{lib:"409084706b801f8d",pos:[0,0,-10],yaw:0,keys:[]},
 "nx-court":{lib:"38096b30b9131685",pos:[18.9,-1.5946487083102603e-8,-14.8],yaw:-.90756,keys:["particles:smoke"]},"nx-forge":{lib:"fcc66d79b76b109e",pos:[22.11785473473295,0,-7.957568494595163],yaw:-.90756,keys:["motion:fire_fg_coals","particles"]},"nx-cistern":{lib:"85d956f6600f336d",pos:[15.703583236444484,0,-14.586880611718946],yaw:-.90756,keys:[]},"nx-sign-bakery":{lib:"599194ee7f4efd81",pos:[14.022735609615019,0,-18.768525175210893],yaw:2.234032653589793,keys:[]},"nx-sign-smithy":{lib:"d8df94003084af39",pos:[23.777264390384975,-1.5946487083102603e-8,-10.831474824789108],yaw:-.90756,keys:[]},
 "nx-tower":{lib:"38f50c9f4fea4583",pos:[14.1,0,16.9],yaw:-2.44347,keys:["sockets"]},"nx-shutters":{lib:"26259f89feb92736",pos:[14.1,0,16.9],yaw:-2.44347,keys:[]},"nx-core-paths":{lib:"9ce1378d47fd8a22",pos:[0,0,0],yaw:0,keys:[]},
};
const lightWant:Record<string,any>={"nx-plaza-l":{pos:[0,1.2,0],color:0xff9040,intensity:2.5,range:7},"nx-welcome-l":{pos:[-3,2.2,-4.3],color:0xffb066,intensity:1.2,range:4},...Object.fromEntries([["e",[9.9,1.96,0]],["n",[0,1.96,9.9]],["w",[-9.9,1.96,0]],["s",[0,1.96,-9.9]]].map(([q,pos])=>[`nx-approach-lamp-${q}-l`,{pos,color:0xffb066,intensity:1.35,range:4.5}]))};
async function lightFold(){const ids=new Set(Object.keys(lightWant));return await new Promise<Record<string,any>>((resolve,reject)=>{const ws=new WebSocket(cfg.url),out:any={};const t=setTimeout(()=>reject(Error("light history timeout")),30000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:"commons-next",id:"arthur-nvp22-light-audit",avatar:cfg.avatar,token:cfg.joinToken,spectate:true}));ws.onerror=()=>reject(Error("light history ws"));ws.onmessage=(ev:any)=>{const m=JSON.parse(ev.data);if(m.type==="error")reject(Error(m.error));if(m.type==="snapshot")ws.send(JSON.stringify({type:"history",verbs:["light"],limit:400}));if(m.type==="history"){for(const r of m.entries??[]){const x=r.args??r;if(!ids.has(x.id))continue;const p=out[x.id]??{};out[x.id]={pos:x.pos??p.pos,color:x.color??p.color,intensity:x.intensity??p.intensity,range:x.range??p.range}}clearTimeout(t);ws.close();resolve(out)}}})}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const d=await census();if(d.count!==21)die(`entity count ${d.count}`);const by=Object.fromEntries(d.entities.map((e:any)=>[e.id,e]));for(const[id,w]of Object.entries(expected)){const e=by[id];if(!e||e.lib!==`store/${w.lib}.glb`||!eq(e.pos,w.pos)||Math.abs((e.yaw??0)-w.yaw)>1e-9||e.scale!==1||!eq(e.compKeys,w.keys))die(`tuple/keys drift ${id}`)}for(const id of Object.keys(lightWant))if(!by[id]||by[id].kind!=="light")die(`light identity missing ${id}`);const lf=await lightFold();if(!eq(lf,lightWant))die(`light fold drift ${JSON.stringify(lf)}`);
const intended=new Set(["nx-shutters|nx-tower","nx-cistern|nx-court","nx-court|nx-sign-bakery","nx-court|nx-sign-smithy"]),models=d.entities.filter((e:any)=>e.bbox&&e.id!=="nx-core-paths"),unclassified:any[]=[];for(let i=0;i<models.length;i++)for(let k=i+1;k<models.length;k++){const a=models[i],b=models[k],g=gap(EO(a),EO(b)),key=[a.id,b.id].sort().join("|");if(g<-.001&&!intended.has(key))unclassified.push([a.id,b.id,g])}if(unclassified.length)die(`unclassified model overlaps ${JSON.stringify(unclassified)}`);
const man=JSON.parse(readFileSync(`${ROOT}/agents/arthur/assets/village_next_core_paths.review.json`,"utf8")),others=d.entities.filter((e:any)=>e.bbox&&e.id!=="nx-core-paths");let min=Infinity;for(const p of man.pavers)for(const e of others){const g=gap(O(p.x,p.z,p.yaw,p.w,p.d),EO(e));min=Math.min(min,g);if(g<-.001)die(`paver overlap ${p.id}/${e.id}`)}if(min<.17)die(`paver clearance ${min}`);if(d.entities.some((e:any)=>e.id.startsWith("mx-")))die("mx id present in commons-next core audit");console.log(JSON.stringify({status:"ALL_PASS",entities:d.count,models:Object.keys(expected).length,lights:Object.keys(lightWant).length,unclassifiedOverlaps:0,intendedAttachments:[...intended],pavers:man.pavers.length,minPaverClearance:min,lightFold:lf},null,2));
