// next-place-core-paths.ts — nvp-21 exact reviewed path placement.
// commons-next only; manifest-driven per-paver micro-SAT; no GUI dependency.
import {readFileSync}from"node:fs";import{createHash}from"node:crypto";
const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-core-paths",SHA="9ce1378d47fd8a227a6935704d750266e73c4e902781df905ae5da251307560c",MSHA="7a78419e12e7042a9b8fb90024468040b1f656469a981f5bfd1936c7989cf24b";const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_next_core_paths.glb`)),mb=readFileSync(`${ROOT}/agents/arthur/assets/village_next_core_paths.review.json`),manifest=JSON.parse(mb.toString());const die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;
if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("reviewed GLB hash drift");if(createHash("sha256").update(mb).digest("hex")!==MSHA)die("review manifest hash drift");if(manifest.pavers.length!==75)die("paver manifest drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e])) as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const before=await geom(),existing=before[ID];if(existing&&!(existing.lib===`store/${SHA.slice(0,16)}.glb`&&existing.pos.every((n:number)=>near(n,0))&&near(existing.yaw??0,0)&&existing.scale===1&&Object.keys(existing.comp??{}).length===0))die("nx-core-paths id collision/drift");const footprints=Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID);let min=Infinity;for(const p of manifest.pavers)for(const e of footprints){const g=gap(O(p.x,p.z,p.yaw,p.w,p.d),EO(e));min=Math.min(min,g);if(g<-.001)die(`paver ${p.id} overlaps ${e.id}: ${g}`)}if(min<.17)die(`micro-clearance regressed: ${min}`);
if(!existing){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","commons-next core paths nvp-21");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==`store/${SHA.slice(0,16)}.glb`)die(`upload path ${lib}`);await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let joined=false,sent=false;const timer=setTimeout(()=>reject(Error("verb timeout")),45_000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-nvp21-paths",avatar:cfg.avatar,token:cfg.joinToken}));ws.onerror=()=>reject(Error("websocket error"));ws.onmessage=(ev:any)=>{const x=JSON.parse(ev.data);if(x.type==="error")reject(Error(`server ${x.error}`));else if(x.type==="snapshot"){joined=true;if(!sent){sent=true;ws.send(JSON.stringify({type:"verb",verb:"spawn",args:{id:ID,lib,pos:[0,0,0],yaw:0,scale:1}}));setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1600)}}}})}else console.log("core paths already live — no verbs");
const after=await geom(),e=after[ID];if(!(e?.lib===`store/${SHA.slice(0,16)}.glb`&&e.pos.every((n:number)=>near(n,0))&&near(e.yaw??0,0)&&e.scale===1&&Object.keys(e.comp??{}).length===0))die("post-place tuple failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,scale:e.scale,pavers:manifest.pavers.length,minClearance:min,verbs:existing?0:1}));
