// next-place-artwalk-h5.ts — artwalk-6 H-5 Möbius entry-gate rollout.
// Exact hash, centered SAT, 1.4m lane gap, corridor, tuples, and idempotence.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";
const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-artwalk-h5",SHA="3c48f921d262907aeabd8b5f808ab21870665ea9d50db37090fee9a95d1520a8",PX=19.79898987322333,PY=-0.015837100520963706,PZ=-24.041630560342615,YAW=-0.7853981633974483;
const MINX=-3.259999990463257,MAXX=3.259999990463257,MINZ=-1.7300000190734863,MAXZ=1.7300000190734863,BW=MAXX-MINX,BD=MAXZ-MINZ,CX=0,CZ=0;
const lights=[{id:`${ID}-l-left`,pos:[17.882730496207788,0.6041628994790363,-25.448773054903842]},{id:`${ID}-l-right`,pos:[21.20613236778456,0.6041628994790363,-22.125371183327072]}]as const;
const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_artwalk_h5.glb`));const die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("reviewed GLB hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e]))as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const cc=Math.cos(YAW),ss=Math.sin(YAW),target=O(PX+CX*cc+CZ*ss,PZ-CX*ss+CZ*cc,YAW,BW,BD),want={lib:`store/${SHA.slice(0,16)}.glb`,pos:[PX,PY,PZ],yaw:YAW,scale:1};const tupleOK=(e:any)=>!!e&&e.lib===want.lib&&e.pos.every((n:number,i:number)=>near(n,want.pos[i]))&&near(e.yaw??0,YAW)&&e.scale===1&&Object.keys(e.comp??{}).length===0,lightOK=(e:any,l:any)=>!!e&&e.kind==="light"&&e.pos.every((n:number,i:number)=>near(n,l.pos[i]));
const before=await geom(),existing=before[ID];if(existing&&!tupleOK(existing))die(`${ID} id collision/drift`);for(const l of lights)if(before[l.id]&&!lightOK(before[l.id],l))die(`${l.id} collision/drift`);if(existing&&lights.some(l=>!before[l.id])||!existing&&lights.some(l=>!!before[l.id]))die("partial prior rollout");
let inner=Infinity,outer=0;for(const[lx,lz]of[[MINX,MINZ],[MAXX,MINZ],[MAXX,MAXZ],[MINX,MAXZ]]){const wx=PX+lx*cc+lz*ss,wz=PZ-lx*ss+lz*cc,r=Math.hypot(wx,wz);inner=Math.min(inner,r);outer=Math.max(outer,r)}if(inner<24||outer>50)die(`art corridor violated ${inner}..${outer}`);
const groundIds=new Set(["nx-core-paths","nx-town-roads"]);let minGap=Infinity,minAgainst="";for(const e of Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID)){const h=e.bbox.max[1]-e.bbox.min[1];if(groundIds.has(e.id)||h<=0.5)continue;const g=gap(target,EO(e));if(g<minGap){minGap=g;minAgainst=e.id}if(g<-.001)die(`footprint overlaps ${e.id}: ${g}`)}if(minGap<1.4)die(`walkable lane pinch ${minGap} against ${minAgainst}`);console.log(JSON.stringify({stage:"preflight",centerRadius:+Math.hypot(PX,PZ).toFixed(6),corridor:{inner:+inner.toFixed(6),outer:+outer.toFixed(6)},minGap:+minGap.toFixed(6),minAgainst,nativeVisual:"waived-by-Bill"}));
if(!existing){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","the half-turn gate — artwalk H-5");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==want.lib)die(`upload path ${lib}`);const verbs:[string,any][]=[["spawn",{id:ID,lib,pos:[PX,PY,PZ],yaw:YAW,scale:1}],...lights.map(l=>["light",{id:l.id,pos:l.pos,color:0xffc98a,intensity:1.35,range:4.6}]as[string,any])];await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let joined=false,i=0;const timer=setTimeout(()=>reject(Error("verb timeout")),45_000);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-artwalk-h5-builder",avatar:cfg.avatar,token:cfg.joinToken}));ws.onerror=()=>reject(Error("websocket error"));ws.onmessage=(ev:any)=>{const x=JSON.parse(ev.data);if(x.type==="error")reject(Error(`server ${x.error}`));else if(x.type==="snapshot"&&!joined){joined=true;const paced=setInterval(()=>{if(i>=verbs.length){clearInterval(paced);setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1800);return}const[verb,args]=verbs[i++];ws.send(JSON.stringify({type:"verb",verb,args}))},700)}}})}else console.log("H-5 already live — zero verbs");
const after=await geom(),e=after[ID];if(!tupleOK(e))die("post-place model tuple failed");for(const l of lights)if(!lightOK(after[l.id],l))die(`post-place light ${l.id} failed`);console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,scale:e.scale,bboxSize:e.bbox.size,compKeys:Object.keys(e.comp??{}),lights:lights.map(l=>({id:l.id,pos:after[l.id].pos})),verbs:existing?0:3}));
