// review-court-ensemble.ts — exact-hash local composition renderer for nvp-16.
import {createServer} from "node:http";import{readFileSync,mkdirSync}from "node:fs";import{join,normalize}from "node:path";import{createHash}from "node:crypto";import{chromium}from "playwright";
const ROOT="/Users/t3rpz/projects/eidoverse-worlds",A=join(ROOT,"agents/arthur/assets"),OUT=join(ROOT,"agents/arthur/reviews/nx-court-ensemble");mkdirSync(OUT,{recursive:true});
const specs=[
 ["court","village_court3.glb","38096b30b9131685be9d8ed829839767ded39dae26e54086dd6604f68cbb7b22",0,0,0],
 ["forge","village_forge3.glb","fcc66d79b76b109e8d826a1a1ad38e06fc09292a2b8c2da0d31f5702f8893596",7.373,1.677,0],
 ["cistern","village_bcistern3.glb","85d956f6600f336d11666b59d53d8e5a889a793aa1b26cbce27b5d993f903f8d",-1.8,2.65,0],
 ["bakery-sign","village_sign_bakery.glb","599194ee7f4efd810735f59b1e2d686797a2c29b65249fdc958913619f8ec85c",-6.13,1.4,Math.PI],
 ["smithy-sign","village_sign_smithy.glb","d8df94003084af390e4f6ef0e15f5d13ade33f8e98ad101b7b0408a9dda577e0",6.13,-1.4,0],
] as const;
const files=new Map<string,Buffer>();for(const [n,f,h]of specs){const b=readFileSync(join(A,f));if(createHash("sha256").update(b).digest("hex")!==h)throw Error(`${n} hash drift`);files.set(n,b);}
const THREE_ROOT=join(ROOT,"node_modules/three"),threeModule=join(THREE_ROOT,"build/three.module.js");
const html=`<!doctype html><style>html,body{margin:0;overflow:hidden}canvas{display:block}</style><script type="module">
import * as THREE from '/three.module.js';import{GLTFLoader}from'/examples/jsm/loaders/GLTFLoader.js';
const r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setSize(960,720);r.outputColorSpace=THREE.SRGBColorSpace;r.shadowMap.enabled=true;document.body.appendChild(r.domElement);
const s=new THREE.Scene();s.background=new THREE.Color(0xcbd6df);const cam=new THREE.PerspectiveCamera(42,960/720,.05,120);const hemi=new THREE.HemisphereLight(0xffffff,0x48505a,2);s.add(hemi);const amb=new THREE.AmbientLight(0xffffff,.45);s.add(amb);const sun=new THREE.DirectionalLight(0xfff1d4,3.2);sun.position.set(8,12,6);sun.castShadow=true;s.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshStandardMaterial({color:0x7f8d70,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;s.add(ground);
const root=new THREE.Group();s.add(root);const specs=${JSON.stringify(specs.map(([n,_f,_h,x,z,yaw])=>({n,x,z,yaw})))};const loader=new GLTFLoader();for(const q of specs){const g=(await loader.loadAsync('/model/'+q.n+'.glb')).scene;g.position.set(q.x,0,q.z);g.rotation.y=q.yaw;g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});root.add(g)}root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());root.position.x-=center.x;root.position.z-=center.z;root.position.y-=box.min.y;root.updateMatrixWorld(true);const target=new THREE.Vector3(0,Math.max(.8,size.y*.35),0),rr=Math.max(size.x,size.z,8);const views={front:[0,Math.max(3,size.y*.6),rr*1.35],right:[rr*1.35,Math.max(3,size.y*.6),0],back:[0,Math.max(3,size.y*.6),-rr*1.35],left:[-rr*1.35,Math.max(3,size.y*.6),0],gameplay:[0,1.65,18]};const coals=root.getObjectByName('fire_fg_coals'),base=coals?.position.y;
window.setView=n=>{cam.position.fromArray(views[n]);cam.lookAt(target);r.render(s,cam)};window.setNight=on=>{s.background.set(on?0x111827:0xcbd6df);hemi.intensity=on?.18:2;amb.intensity=on?.04:.45;sun.intensity=on?.15:3.2;r.render(s,cam)};window.setPhase=p=>{if(coals&&base!==undefined)coals.position.y=base+.014*Math.sin(p);r.render(s,cam)};window.setView('front');window.ready=true;window.stats={bounds:{min:box.min.toArray(),max:box.max.toArray(),size:size.toArray()}};
</script>`;
const server=createServer((req,res)=>{const u=(req.url??'/').split('?')[0];try{if(u==='/'){res.setHeader('content-type','text/html');res.end(html);return}if(u==='/three.module.js'){res.setHeader('content-type','text/javascript');res.end(readFileSync(threeModule));return}if(u==='/three.core.js'){res.setHeader('content-type','text/javascript');res.end(readFileSync(join(THREE_ROOT,'build/three.core.js')));return}if(u.startsWith('/examples/jsm/')){const p=join(THREE_ROOT,normalize(u.slice(1)));let x=readFileSync(p,'utf8').replaceAll("from 'three'","from '/three.module.js'").replaceAll('from "three"','from "/three.module.js"');res.setHeader('content-type','text/javascript');res.end(x);return}const m=u.match(/^\/model\/(.+)\.glb$/);if(m&&files.has(m[1])){res.setHeader('content-type','model/gltf-binary');res.end(files.get(m[1]));return}res.statusCode=404;res.end('not found')}catch(e){res.statusCode=500;res.end(String(e))}});await new Promise<void>(q=>server.listen(0,'127.0.0.1',q));const addr=server.address();if(!addr||typeof addr==='string')throw Error('no addr');const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:960,height:720}});p.on('console',m=>console.error('BROWSER',m.type(),m.text()));p.on('pageerror',e=>console.error('PAGEERROR',e.message));p.on('requestfailed',q=>console.error('REQUESTFAILED',q.url(),q.failure()?.errorText));await p.goto(`http://127.0.0.1:${addr.port}/`,{waitUntil:'networkidle'});await p.waitForFunction(()=>window.ready===true);for(const v of ['front','right','back','left','gameplay']){await p.evaluate(x=>window.setView(x),v);await p.screenshot({path:join(OUT,v+'.png')})}await p.evaluate(()=>{window.setView('gameplay');window.setNight(true)});await p.screenshot({path:join(OUT,'night.png')});await p.evaluate(()=>{window.setNight(false);window.setView('front');window.setPhase(0)});await p.screenshot({path:join(OUT,'motion-a.png')});await p.evaluate(()=>window.setPhase(Math.PI/2));await p.screenshot({path:join(OUT,'motion-b.png')});console.log(JSON.stringify(await p.evaluate(()=>window.stats),null,2));}finally{await b.close();server.close();}
