// waysign-place-woodyard-2.ts — waysign-11 R2-4 reseat: emblem-collapse
// fix on nx-sign-woodyard-001 (saw-buck scale-class, family R2 root).
// Waysign lane owns nx-sign-<trade>-NNN only; nx-town-woodyard is
// read-only host truth (artwalk-39: anchor re-derived from CURRENT host
// tuple this tick — host lib verified 1f2c6f592095b204, intentional
// old-gen tex-85 freeze, interior-19; live bbox law anchor [0,2.05,1.25]
// under the open-front eave, sibling b11 rider back wall z −0.80 no
// contact). Reseat = remove + spawn over one WS (re-place law: spawn
// alone never moves a standing entity). Comp bag: signs carry none;
// expected {} on both sides. v2 build f46e12ae: envelope x/z
// byte-identical to 58f5cbe3 (decode-verified) → SAT-neutral; only y
// extends (board dropped 0.45→0.52, glyph within face).
// Window note: this completes a sibling waysign-11 window that died
// pre-place (12:17 build, no live mutation) — recovery class artwalk-32.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-sign-woodyard-001",HOST="nx-town-woodyard",PREV="58f5cbe3272aa7a87a6fe8ae0d6e825d2e42b3809592a94b5e923710aff25f11",SHA="f46e12aeeea8af74d29f3fec939cd324c368b8a1a602444f45370bc909384afc",HOST_LIB="store/1f2c6f592095b204.glb",LOCAL:[number,number,number]=[0,2.05,1.25];const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws",""),bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_sign_woodyard3.glb`)),die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("candidate GLB hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e]))as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const before=await geom(),host=before[HOST];if(!host||host.lib!==HOST_LIB||host.scale!==1)die("woodyard host drift");const YAW=host.yaw??0,c=Math.cos(YAW),s=Math.sin(YAW),POS:[number,number,number]=[host.pos[0]+LOCAL[0]*c+LOCAL[2]*s,host.pos[1]+LOCAL[1],host.pos[2]-LOCAL[0]*s+LOCAL[2]*c];const exist=before[ID];if(!exist)die(`${ID} not standing — this placer only reseats`);if(!exist.pos.every((n:number,i:number)=>near(n,POS[i]))||!near(exist.yaw??0,YAW)||exist.scale!==1)die(`${ID} live pose drift: pos=${exist.pos} yaw=${exist.yaw} want ${POS}/${YAW}`);const liveLib=exist.lib;if(!(liveLib===`store/${PREV.slice(0,16)}.glb`||liveLib===`store/${SHA.slice(0,16)}.glb`))die(`${ID} live lib drift: ${liveLib}`);if(liveLib===`store/${SHA.slice(0,16)}.glb`){if(Object.keys(exist.comp??{}).length)die(`${ID} unexpected comp bag on rerun`);console.log(JSON.stringify({status:"ALREADY_LIVE_NO_VERBS",id:ID,lib:liveLib,pos:POS,yaw:YAW,verbs:0}));process.exit(0)}
if(Object.keys(exist.comp??{}).length)die(`${ID} expected empty comp bag, found ${JSON.stringify(Object.keys(exist.comp))} — capture/reapply needed`);
// Eave rider: overlap with the host is intentional (flush eave mount);
// every OTHER solid must clear. Ground-layer meshes exempt both ways
// (nvp-109..132 law; waysign-5/woodyard-1 precedent): approach-lane
// pavers carry lamp posts whose compound bboxes envelope half the
// village; the sign hangs at y 1.43..2.05 in open air. Lamps and all
// other solids remain in the collision set. Decoded rider bbox
// (sign-local, v2 f46e12ae): x[−0.262,0.262] z[−0.030,0.294] → center
// (0, 0.132), half extents (0.262, 0.162), padded (0.5, 0.32) same as
// woodyard-1 (envelope x/z byte-identical — verified this tick).
const CX=0,CZ=0.132,HW=0.5,HD=0.32,target=O(POS[0]+CX*c+CZ*s,POS[2]-CX*s+CZ*c,YAW,HW,HD),groundIds=new Set(["nx-core-paths","nx-town-roads","nx-town-streetlamps","nx-approach-nw-lane-001","nx-approach-ne-lane-002","nx-approach-sw-lane-003"]);let minGap=Infinity,minAgainst="";for(const e of Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID&&e.id!==HOST)){const h=e.bbox.max[1]-e.bbox.min[1];if(groundIds.has(e.id)||h<=.5)continue;const g=gap(target,EO(e));if(g<minGap){minGap=g;minAgainst=e.id}if(g<-.001)die(`sign overlaps ${e.id}: ${g}`)}
console.log(JSON.stringify({stage:"preflight",host:HOST,hostLib:host.lib,hostLocal:LOCAL,pos:POS,yaw:YAW,minGap:+minGap.toFixed(6),minAgainst,classification:"intentional woodyard-eave rider; host-only SAT exemption",visual:"zai-vision v2 4/4 18m + 3/3 8m + 3/3 isolated + 3/3 oblique (native provider down 2 attempts, disclosed)"}));
const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","woodyard trade sign — waysign-11");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==`store/${SHA.slice(0,16)}.glb`)die(`upload path ${lib}`);
const verbs:Array<[string,any]>=[["remove",{id:ID}],["spawn",{id:ID,lib:`store/${SHA.slice(0,16)}.glb`,pos:POS,yaw:YAW,scale:1}]];await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url);let joined=false,i=0;const timer=setTimeout(()=>reject(Error("verb timeout")),90_000);const paced=setInterval(()=>{if(!joined||i>=verbs.length)return;const[v,a]=verbs[i++];ws.send(JSON.stringify({type:"verb",verb:v,args:a}));if(i===verbs.length)setTimeout(()=>{clearInterval(paced);clearTimeout(timer);ws.close();resolve()},1600)},650);ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-waysign11-woodyard",avatar:cfg.avatar,token:cfg.joinToken,agent:true,agentToken:cfg.agentToken}));ws.onerror=()=>reject(Error("websocket error"));ws.onmessage=(ev:any)=>{const x=JSON.parse(ev.data);if(x.type==="error")reject(Error(`server ${x.error}`));else if(x.type==="snapshot")joined=true}});
const after=await geom(),e=after[ID];if(!(e?.lib===`store/${SHA.slice(0,16)}.glb`&&e.pos.every((n:number,i:number)=>near(n,POS[i]))&&near(e.yaw??0,YAW)&&e.scale===1))die("post-place tuple failed");if(Object.keys(e.comp??{}).length)die("post-place comp bag not empty");const dx=e.pos[0]-host.pos[0],dz=e.pos[2]-host.pos[2],lx=dx*c-dz*s,lz=dx*s+dz*c;if(!near(lx,LOCAL[0])||!near(lz,LOCAL[2])||!near(e.pos[1]-host.pos[1],LOCAL[1]))die("host-relative anchor failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,hostLocal:[lx,e.pos[1]-host.pos[1],lz],compKeys:Object.keys(e.comp??{}),verbs:2}));
