// waysign-place-stable-1.ts — waysign-1: LIVERY SIGN rider on nx-town-stable.
// Waysign lane owns nx-sign-<trade>-NNN only; nx-town-stable is read-only
// host truth (artwalk-39: anchor derived from CURRENT host tuple).
// Sign plate back (local z=0) flush-touches the stable's road-facing back
// wall (host local z=2.1); glyph face (+z) points down the E road; board
// top at the wall-top eave line. Host-pair SAT exemption explicit.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-sign-stable-001",HOST="nx-town-stable",SHA="afee37dd9a5b5d67abd1b3d14063c09aefafa7794f057925366b6fdd21481836",HOST_LIB="store/5beff62ed41ca6cf.glb",LOCAL:[number,number,number]=[0,0,2.1];const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws","");const bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_sign_stable3.glb`)),die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("reviewed GLB hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e]))as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const before=await geom(),host=before[HOST];if(!host||host.lib!==HOST_LIB||host.scale!==1)die("stable host drift");const YAW=host.yaw??0,c=Math.cos(YAW),s=Math.sin(YAW),POS:[number,number,number]=[host.pos[0]+LOCAL[0]*c+LOCAL[2]*s,host.pos[1]+LOCAL[1],host.pos[2]-LOCAL[0]*s+LOCAL[2]*c],want={lib:`store/${SHA.slice(0,16)}.glb`,pos:POS,yaw:YAW,scale:1};const tupleOK=(e:any)=>!!e&&e.lib===want.lib&&e.pos.every((n:number,i:number)=>near(n,want.pos[i]))&&near(e.yaw??0,YAW)&&e.scale===1&&Object.keys(e.comp??{}).length===0,existing=before[ID];if(existing&&!tupleOK(existing))die(`${ID} id collision/drift`);
// Wall rider: overlap with the host is intentional (flush mount); every
// OTHER solid must clear. Ground-layer meshes exempt both directions.
const MINX=-0.25,MAXX=0.25,MINZ=0,MAXZ=0.324,CX=0,CZ=0.162,target=O(POS[0]+CX*c+CZ*s,POS[2]-CX*s+CZ*c,YAW,MAXX-MINX,MAXZ-MINZ),groundIds=new Set(["nx-core-paths","nx-town-roads","nx-town-streetlamps"]);let minGap=Infinity,minAgainst="";for(const e of Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID&&e.id!==HOST)){const h=e.bbox.max[1]-e.bbox.min[1];if(groundIds.has(e.id)||h<=.5)continue;const g=gap(target,EO(e));if(g<minGap){minGap=g;minAgainst=e.id}if(g<-.001)die(`sign overlaps ${e.id}: ${g}`)}
console.log(JSON.stringify({stage:"preflight",host:HOST,hostLib:host.lib,hostLocal:LOCAL,pos:POS,yaw:YAW,minGap:+minGap.toFixed(6),minAgainst,classification:"intentional stable-wall rider; host-only SAT exemption",visual:"zai-vision v2 ACCEPT (native vision provider down this tick)"}));
if(!existing){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","livery trade sign — waysign-1");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==want.lib)die(`upload path ${lib}`);await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url),timer=setTimeout(()=>reject(Error("verb timeout")),45_000);let sent=false;ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-waysign-1-builder",avatar:cfg.avatar,token:cfg.joinToken,agent:true,agentToken:cfg.agentToken}));ws.onerror=()=>reject(Error("websocket"));ws.onmessage=(ev:any)=>{const m=JSON.parse(ev.data);if(m.type==="error")reject(Error(`server ${m.error}`));else if(m.type==="snapshot"&&!sent){sent=true;ws.send(JSON.stringify({type:"verb",verb:"spawn",args:{id:ID,lib:want.lib,pos:POS,yaw:YAW,scale:1}}));setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1800)}}})}else console.log("waysign-1 already live — zero verbs");
const after=await geom(),e=after[ID];if(!tupleOK(e))die("post-place tuple failed");const dx=e.pos[0]-host.pos[0],dz=e.pos[2]-host.pos[2],lx=dx*c-dz*s,lz=dx*s+dz*c;if(!near(lx,LOCAL[0])||!near(lz,LOCAL[2])||!near(e.pos[1]-host.pos[1],LOCAL[1]))die("host-relative anchor failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,hostLocal:[lx,e.pos[1]-host.pos[1],lz],bboxSize:e.bbox.size,verbs:existing?0:1}));
