// waysign-place-mill-1.ts — waysign-6: MILL SIGN rider on nx-town-windmill.
// Waysign lane owns nx-sign-<trade>-NNN only; nx-town-windmill is read-only
// host truth (artwalk-39: anchor derived from CURRENT host tuple; local
// source village_windmill3.glb hash-matches live lib 0993836012d1b17d this
// tick — anchor math may use source: rceil slab front edge z 2.6 underside
// y 2.8, front wall face z 2.4, door lane |x|<0.7).
// Sibling artwalk b10 `four-wind-crown` owns the wall center (live bbox
// local x ±1.125, y 2.22..2.87) — sign sites at host-local x −1.6 (world
// +z/north, away from the struct-lane millrace to the south), bracket
// flush under the rceil front edge, board hanging proud of the wall face.
import{readFileSync}from"node:fs";import{createHash}from"node:crypto";const ROOT="/Users/t3rpz/projects/eidoverse-worlds",WORLD="commons-next",ID="nx-sign-mill-001",HOST="nx-town-windmill",SHA="5b6a55bdea1c2316b5e21ab13c01b7723f6aff2af035da82f745f61c16feeb54",HOST_LIB="store/0993836012d1b17d.glb",LOCAL:[number,number,number]=[-1.6,2.78,2.5];const cfg=JSON.parse(readFileSync(`${ROOT}/agents/arthur/config.json`,"utf8")),base=cfg.url.replace("wss://","https://").replace("ws://","http://").replace("/ws",""),bytes=new Uint8Array(readFileSync(`${ROOT}/agents/arthur/assets/village_sign_mill3.glb`)),die=(m:string):never=>{throw Error(m)},near=(a:number,b:number)=>Math.abs(a-b)<1e-6;if(createHash("sha256").update(bytes).digest("hex")!==SHA)die("reviewed GLB hash drift");
async function geom(){const r=await fetch(`${base}/geom?world=${WORLD}`);if(!r.ok)die(`geom ${r.status}`);const d:any=await r.json();return Object.fromEntries((d.entities??[]).map((e:any)=>[e.id,e]))as Record<string,any>}
type O={c:[number,number],u:[number,number],v:[number,number],hu:number,hv:number};function O(x:number,z:number,y:number,w:number,d:number):O{const c=Math.cos(y),s=Math.sin(y);return{c:[x,z],u:[c,-s],v:[s,c],hu:w/2,hv:d/2}}function EO(e:any){const b=e.bbox,y=e.yaw??0,c=Math.cos(y),s=Math.sin(y),x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;return O(e.pos[0]+x*c+z*s,e.pos[2]-x*s+z*c,y,b.max[0]-b.min[0],b.max[2]-b.min[2])}function gap(A:O,B:O){let best=-Infinity;for(const x of[A.u,A.v,B.u,B.v]){const dd=Math.abs((B.c[0]-A.c[0])*x[0]+(B.c[1]-A.c[1])*x[1]),ra=A.hu*Math.abs(A.u[0]*x[0]+A.u[1]*x[1])+A.hv*Math.abs(A.v[0]*x[0]+A.v[1]*x[1]),rb=B.hu*Math.abs(B.u[0]*x[0]+B.u[1]*x[1])+B.hv*Math.abs(B.v[0]*x[0]+B.v[1]*x[1]);best=Math.max(best,dd-ra-rb)}return best}
const before=await geom(),host=before[HOST];if(!host||host.lib!==HOST_LIB||host.scale!==1)die("windmill host drift");const YAW=host.yaw??0,c=Math.cos(YAW),s=Math.sin(YAW),POS:[number,number,number]=[host.pos[0]+LOCAL[0]*c+LOCAL[2]*s,host.pos[1]+LOCAL[1],host.pos[2]-LOCAL[0]*s+LOCAL[2]*c],want={lib:`store/${SHA.slice(0,16)}.glb`,pos:POS,yaw:YAW,scale:1};const tupleOK=(e:any)=>!!e&&e.lib===want.lib&&e.pos.every((n:number,i:number)=>near(n,want.pos[i]))&&near(e.yaw??0,YAW)&&e.scale===1&&Object.keys(e.comp??{}).length===0,existing=before[ID];if(existing&&!tupleOK(existing))die(`${ID} id collision/drift`);
// Eave rider: overlap with the host is intentional (flush under the rceil
// front edge); every OTHER solid must clear. Ground-layer meshes exempt
// both ways (nvp-109..132 law; dyer/woodyard precedent). The sign hangs
// at y 2.13..2.78 in open air above ground level. Lamps and all other
// solids — including sibling artwalk b10 crown (expected clearance
// +0.203m by exact extents: 1.6 − 0.272 − 1.125) — remain in the set.
// Decoded rider bbox (sign-local): x[−0.272,0.272] z[−0.03,0.291] →
// center (0, 0.13), half extents (0.272, 0.161) — EXACT, unpadded (the
// woodyard's padding would false-fail the b10 adjacency at −0.025).
const CX=0,CZ=0.13,HW=0.272,HD=0.161,target=O(POS[0]+CX*c+CZ*s,POS[2]-CX*s+CZ*c,YAW,HW,HD),groundIds=new Set(["nx-core-paths","nx-town-roads","nx-town-streetlamps","nx-approach-nw-lane-001","nx-approach-ne-lane-002","nx-approach-sw-lane-003"]);let minGap=Infinity,minAgainst="";for(const e of Object.values(before).filter((e:any)=>e.bbox&&e.id!==ID&&e.id!==HOST)){const h=e.bbox.max[1]-e.bbox.min[1];if(groundIds.has(e.id)||h<=.5)continue;const g=gap(target,EO(e));if(g<minGap){minGap=g;minAgainst=e.id}if(g<-.001)die(`sign overlaps ${e.id}: ${g}`)}
console.log(JSON.stringify({stage:"preflight",host:HOST,hostLib:host.lib,hostLocal:LOCAL,pos:POS,yaw:YAW,minGap:+minGap.toFixed(6),minAgainst,classification:"intentional windmill-eave rider; host-only SAT exemption; b10 crown in collision set (+0.203 expected)",visual:"zai-vision v5 ACCEPT + 8m gate PASS (native vision provider down 6th tick)"}));
if(!existing){const u=new URL(`${base}/upload`);u.searchParams.set("token",cfg.agentToken);u.searchParams.set("name","mill trade sign — waysign-6");u.searchParams.set("by",cfg.id);let lib="";for(let a=1;a<=5;a++){const r=await fetch(u,{method:"POST",body:bytes});if(r.ok){lib=(await r.json()).path;break}if(r.status===429&&a<5){await new Promise(q=>setTimeout(q,25_000));continue}die(`upload ${r.status}`)}if(lib!==want.lib)die(`upload path ${lib}`);await new Promise<void>((resolve,reject)=>{const ws=new WebSocket(cfg.url),timer=setTimeout(()=>reject(Error("verb timeout")),45_000);let sent=false;ws.onopen=()=>ws.send(JSON.stringify({type:"join",world:WORLD,id:"arthur-waysign-6-builder",avatar:cfg.avatar,token:cfg.joinToken,agent:true,agentToken:cfg.agentToken}));ws.onerror=()=>reject(Error("websocket"));ws.onmessage=(ev:any)=>{const m=JSON.parse(ev.data);if(m.type==="error")reject(Error(`server ${m.error}`));else if(m.type==="snapshot"&&!sent){sent=true;ws.send(JSON.stringify({type:"verb",verb:"spawn",args:{id:ID,lib:want.lib,pos:POS,yaw:YAW,scale:1}}));setTimeout(()=>{clearTimeout(timer);ws.close();resolve()},1800)}}})}else console.log("waysign-6 already live — zero verbs");
const after=await geom(),e=after[ID];if(!tupleOK(e))die("post-place tuple failed");const dx=e.pos[0]-host.pos[0],dz=e.pos[2]-host.pos[2],lx=dx*c-dz*s,lz=dx*s+dz*c;if(!near(lx,LOCAL[0])||!near(lz,LOCAL[2])||!near(e.pos[1]-host.pos[1],LOCAL[1]))die("host-relative anchor failed");console.log(JSON.stringify({status:"PLACED_VERIFIED",id:ID,lib:e.lib,pos:e.pos,yaw:e.yaw,hostLocal:[lx,e.pos[1]-host.pos[1],lz],bboxSize:e.bbox.size,verbs:existing?0:1}));
